version: "3"

services:
    renderd:
        image: overv/openstreetmap-tile-server
        command: "run"
        restart: always
        environment:
            - ALLOW_CORS=1
        volumes:
            - openstreetmap-data:/var/lib/postgresql/10/main
            - openstreetmap-rendered-tiles:/var/lib/mod_tile
        ports:
            - "10080:80"

volumes:
    openstreetmap-data:
        external: true
    openstreetmap-rendered-tiles:
        external: true
