version: '3'
volumes:
  postgres_data:
services:
  postgres-db:
    build:
      context: ./postgres-db/
      dockerfile: Dockerfile
    image: smarttraffic-smdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
#    Environments variables for connection...
    env_file: ./postgres-db/.env
    networks:
      - smarttraffic_conn
  django-server:
    build:
      context: ./django-server
      dockerfile: Dockerfile
    image: smarttraffic/smserver
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    networks:
      - smarttraffic_conn
    restart: always

networks:
  smarttraffic_conn:
    driver: bridge