version: '3'

services:
  postgres:
    container_name: django-database
    image: mdillon/postgis:11
    
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    # env_file: ./postgres-db/.env
    networks:
      - smarttraffic_conn
  pgrouting:
    image: pgrouting/pgrouting:v2.6.3-postgresql_11
    container_name: street-network-database
    ports:
      - "6000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres

networks:
  smarttraffic_conn:
    driver: bridge

volumes:
  db-data:
    driver: local
