version: '3'
volumes:
  postgres10-postgis2.5:
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres10-postgis2.5
    container_name: postgres10-postgis2.5
    volumes:
      - postgres10-postgis2.5:/var/lib/postgresql/data
      - ./backups:/opt/backups
    networks:
      - postgres_conn
    ports:
      - '5432:5432'
    env_file: .env

networks:
  postgres_conn:
    driver: bridge