version: "3"

services:
    postgres:
        image: mdillon/postgis:11
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: always
        ports:
            - "15432:5432"
        env_file:
            - postgres.env
        # networks:
        #     - sca_network

    smartcity:
        image: smarttraffic/smartcity-asuncion:test
        env_file:
            - smartcity.env
        # build:
        # context: ../
        # networks:
        #     - dsne-django-nginx
        depends_on:
            - postgres
        volumes:
            # - smwebsite-static:/home/user/static
            - static-files:/home/user/static
        ports:
            - 9000:8888

# networks:
#     sca_network:
#         driver: bridge

volumes:
    db-data:
        driver: local
    static-files:
        driver: local
